"""Console entry point: ``ikaros-mem-v5`` runs the V5 MCP server.

The MCP server is the only public interface of the V5 memory engine. Hermes
Agent launches it as a subprocess (see hermes-mcp-v5.json generated by install.py).
"""
from __future__ import annotations

from v5.mcp_server import main

if __name__ == "__main__":
    main()
